class Consts:
    INTERVALS = [
        "KLINE_INTERVAL_1MINUTE",
        "KLINE_INTERVAL_3MINUTE",
        "KLINE_INTERVAL_5MINUTE",
        "KLINE_INTERVAL_15MINUTE",
        "KLINE_INTERVAL_30MINUTE",
        "KLINE_INTERVAL_1HOUR",
        "KLINE_INTERVAL_2HOUR",
        "KLINE_INTERVAL_4HOUR",
        "KLINE_INTERVAL_6HOUR",
        "KLINE_INTERVAL_8HOUR",
        "KLINE_INTERVAL_12HOUR",
        "KLINE_INTERVAL_1DAY",
        "KLINE_INTERVAL_3DAY",
        "KLINE_INTERVAL_1WEEK",
        "KLINE_INTERVAL_1MONTH",
    ]